[package]
name = "edatime-bin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "edatime"
path = "src/main.rs"

[dependencies]
edatime-core = { path = "../edatime-core" }
edatime-service = { path = "../edatime-service" }
tokio.workspace = true
polars.workspace = true
axum.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
