// services/api/index.ts
// Re-export everything from client, endpoints, and types

export { getJson, postJson, fetchArrow, buildUrl, _inflightJson, _inflightArrow } from './client';
export type {
  ColumnMetadata,
  TimeRange,
  Histogram,
  ColumnProfile,
  DatasetMetadata,
  MetadataResponse,
  PreviewResponse,
  IngestResponse,
  DbTablesResponse,
  TimeseriesRangeResponse,
  TimeseriesRequest,
  ArrowResponse,
  ScatterPointsResponse,
  ScatterRequest,
  CorrelationsResponse,
  CorrelationMatrixResponse,
  RollingBand,
  RollingResponse,
  RollingRequest,
  AnomalyRegion,
  AnomalyResponse,
  AnomalyRequest,
  FftResult,
  FftResponse,
  FftRequest,
  SpectrogramResponse,
  SpectrogramRequest,
} from './types';
export {
  fetchMetadata,
  fetchTimeseriesRange,
  fetchTimeseriesData,
  fetchRollingBands,
  fetchAnomalies,
  fetchFftData,
  fetchSpectrogram,
  fetchScatterCorrelations,
  fetchCorrelationMatrix,
  fetchScatterPoints,
  uploadPreview,
  uploadIngest,
  dbConnect,
  dbTables,
  dbLoad,
  dbDisconnect,
  fetchSampleETTm2,
  clearSampleCache,
} from './endpoints';