//! Plan-aware validation, preview, and full working-dataset export.

use std::collections::BTreeMap;
use std::io::{Cursor, Write};

use axum::{
    Json,
    extract::State,
    http::{HeaderValue, header},
    response::{IntoResponse, Response},
};
use chrono::{DateTime, Utc};
use polars::prelude::DataType;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use zip::{CompressionMethod, ZipWriter, write::FileOptions};

use crate::error::AppError;
use crate::handlers::routes::shared::{ExecutionIdentity, add_execution_identity_headers};
use crate::streaming_export::lazy_parquet_response;
use edatime_query::cleaning::{
    CleaningPlanDto, CleaningStageDto, ColumnSelectMode, DuplicateKeep, FillNullDirection,
    RangeMode, ResampleAggregationMethod, TimeRangeMode, compile_cleaning_plan, semantic_hash,
};
use edatime_query::derived::parse_derived_expression;
use edatime_store::artifacts::ArtifactStorageUsage;
use edatime_store::jobs::JobKind;
use edatime_store::state::AppState;
use edatime_store::versions::DatasetVersionRecord;

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CleaningHandoffManifest {
    pub schema_version: u16,
    pub exported_at: DateTime<Utc>,
    pub execution_provenance: ManifestExecutionProvenance,
    pub source_version: DatasetVersionRecord,
    pub root_source_version: DatasetVersionRecord,
    pub plan_hash: String,
    pub canonical_plan: CleaningPlanDto,
    pub before: ManifestDatasetSummary,
    pub after: ManifestDatasetSummary,
    pub artifact_checksums: ManifestArtifactChecksums,
}

/// Versioned backend facts needed to reproduce the semantics of a handoff.
/// These are generated by the executing service, never accepted from a client.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ManifestExecutionProvenance {
    pub application: &'static str,
    pub application_version: &'static str,
    pub plan_schema_version: u16,
    pub semantic_hash_algorithm: &'static str,
    pub execution_mode: &'static str,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ManifestDatasetSummary {
    pub rows: usize,
    pub columns: usize,
    pub time_range: Option<crate::handlers::routes::metadata::TimeRange>,
    pub null_count: usize,
    pub non_finite_count: usize,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ManifestArtifactChecksums {
    pub source_dataset: String,
    pub source_schema: String,
    pub canonical_plan: String,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PlanRequestEnvelope {
    pub plan: CleaningPlanDto,
    pub expected_plan_hash: Option<String>,
    pub expected_source_version_id: String,
    pub expected_dataset_revision: u64,
}

/// Exact, plan-aware bounds that can be added as canonical range stages
/// instead of invoking the legacy destructive outlier endpoint.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct OutlierProposalRequest {
    #[serde(flatten)]
    pub context: PlanRequestEnvelope,
    pub columns: Vec<String>,
    pub method: String,
    pub threshold: f64,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct OutlierRangeProposal {
    pub column: String,
    pub from: f64,
    pub to: f64,
    pub retain_nulls: bool,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct OutlierProposalResponse {
    pub source_version: DatasetVersionRecord,
    pub dataset_revision: u64,
    pub plan_hash: String,
    pub method: String,
    pub threshold: f64,
    pub ranges: Vec<OutlierRangeProposal>,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CleaningDataExportRequest {
    #[serde(flatten)]
    pub context: PlanRequestEnvelope,
    #[serde(default = "default_export_format")]
    pub format: String,
    #[serde(default)]
    pub output_columns: Option<Vec<String>>,
}

/// A backend-owned source-code export. The plan envelope is validated and
/// compiled before code is produced, preventing a browser-only plan snapshot
/// from being handed off as executable provenance.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CleaningCodeExportRequest {
    #[serde(flatten)]
    pub context: PlanRequestEnvelope,
    pub language: CleaningCodeLanguage,
}

#[derive(Debug, Clone, Copy, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum CleaningCodeLanguage {
    Python,
    Rust,
}

fn default_export_format() -> String {
    "parquet".to_string()
}

fn code_quote(value: &str) -> String {
    // JSON strings are valid quoted literals in both generated Python and
    // Rust source, and keep arbitrary column names from escaping the script.
    serde_json::to_string(value).expect("string serialization cannot fail")
}

fn code_number(value: f64) -> String {
    if value == 0.0 {
        "0.0".to_string()
    } else {
        value.to_string()
    }
}

/// Match the compiler's physical comparison values for Date and Datetime
/// columns. Generated code compares `cast(Int64)` values, so emitting raw
/// epoch milliseconds would silently disagree for dates and µs/ns datetimes.
fn split_native_boundaries(
    train_end_ms: f64,
    validation_end_ms: f64,
    embargo_ms: f64,
    time_dtype: &DataType,
) -> Result<[i64; 4], AppError> {
    Ok([
        edatime_core::temporal::epoch_ms_to_native(train_end_ms, time_dtype, true)?,
        edatime_core::temporal::epoch_ms_to_native(train_end_ms + embargo_ms, time_dtype, true)?,
        edatime_core::temporal::epoch_ms_to_native(validation_end_ms, time_dtype, true)?,
        edatime_core::temporal::epoch_ms_to_native(
            validation_end_ms + embargo_ms,
            time_dtype,
            true,
        )?,
    ])
}

fn validate_codegen_support(plan: &CleaningPlanDto) -> Result<(), AppError> {
    if plan
        .stages
        .iter()
        .any(|stage| stage.enabled() && matches!(stage, CleaningStageDto::AdaptiveLine { .. }))
    {
        return Err(AppError::bad_request(
            "Backend code export does not yet support adaptive-line stages; export the canonical plan JSON or remove that stage before requesting code",
        ));
    }
    Ok(())
}

fn python_predicate(column: &str, from: f64, to: f64) -> String {
    format!(
        "(pl.col({}).cast(pl.Float64) >= {}) & (pl.col({}).cast(pl.Float64) <= {})",
        code_quote(column),
        code_number(from.min(to)),
        code_quote(column),
        code_number(from.max(to)),
    )
}

fn generate_python_polars(
    plan: &CleaningPlanDto,
    version: &DatasetVersionRecord,
    hash: &str,
    time_dtype: &DataType,
) -> Result<String, AppError> {
    let mut lines = vec![
        "# EdaTime backend-generated canonical plan artifact (v1).".to_string(),
        format!(
            "# source version: {} @ revision {}",
            version.id, version.revision
        ),
        format!("# plan hash: {hash}"),
        "# Requires a Polars runtime compatible with the generated v1 operators.".to_string(),
        String::new(),
        "import math".to_string(),
        "import polars as pl".to_string(),
        String::new(),
        "def apply_edatime_plan(lf: pl.LazyFrame) -> pl.LazyFrame:".to_string(),
    ];
    let mut executable = false;
    for stage in &plan.stages {
        if !stage.enabled() || matches!(stage, CleaningStageDto::Annotation { .. }) {
            continue;
        }
        executable = true;
        match stage {
            CleaningStageDto::TimeRange {
                start_ms,
                end_ms,
                mode,
                ..
            } => {
                let predicate = python_predicate(&plan.time_column, *start_ms, *end_ms);
                let expression = if *mode == TimeRangeMode::KeepInside {
                    predicate
                } else {
                    format!("({predicate}).not() | ({predicate}).is_null()")
                };
                lines.push(format!("    lf = lf.filter({expression})"));
            }
            CleaningStageDto::ColumnRange {
                column,
                from,
                to,
                mode,
                retain_nulls,
                ..
            } => {
                let predicate = python_predicate(column, *from, *to);
                let expression = if *mode == RangeMode::KeepInside {
                    if *retain_nulls {
                        format!("pl.col({}).is_null() | ({predicate})", code_quote(column))
                    } else {
                        predicate
                    }
                } else {
                    format!("({predicate}).not() | ({predicate}).is_null()")
                };
                lines.push(format!("    lf = lf.filter({expression})"));
            }
            CleaningStageDto::MissingValue {
                column,
                drop_nulls,
                drop_non_finite,
                ..
            } => {
                let value = format!("pl.col({})", code_quote(column));
                let predicate = match (*drop_nulls, *drop_non_finite) {
                    (true, true) => format!("{value}.is_not_null() & {value}.is_finite()"),
                    (true, false) => format!("{value}.is_not_null()"),
                    (false, true) => format!("{value}.is_null() | {value}.is_finite()"),
                    (false, false) => unreachable!("validated plan"),
                };
                lines.push(format!("    lf = lf.filter({predicate})"));
            }
            CleaningStageDto::Deduplicate { columns, keep, .. } => {
                let columns = columns
                    .iter()
                    .map(|column| code_quote(column))
                    .collect::<Vec<_>>()
                    .join(", ");
                let keep = if *keep == DuplicateKeep::First {
                    "first"
                } else {
                    "last"
                };
                lines.push(format!(
                    "    lf = lf.unique(subset=[{columns}], keep={keep:?}, maintain_order=True)"
                ));
            }
            CleaningStageDto::ColumnSelect { columns, mode, .. } => {
                let columns = columns
                    .iter()
                    .map(|column| code_quote(column))
                    .collect::<Vec<_>>()
                    .join(", ");
                if *mode == ColumnSelectMode::Keep {
                    lines.push(format!(
                        "    lf = lf.select([pl.col(column) for column in [{columns}]])"
                    ));
                } else {
                    lines.push(format!("    lf = lf.drop([{columns}])"));
                }
            }
            CleaningStageDto::Sort {
                columns,
                descending,
                nulls_last,
                ..
            } => {
                let columns = columns
                    .iter()
                    .map(|column| code_quote(column))
                    .collect::<Vec<_>>()
                    .join(", ");
                lines.push(format!("    lf = lf.sort(by=[{columns}], descending={}, nulls_last={}, maintain_order=True)", if *descending { "True" } else { "False" }, if *nulls_last { "True" } else { "False" }));
            }
            CleaningStageDto::FillNull {
                columns,
                strategy,
                limit,
                ..
            } => {
                let strategy = if *strategy == FillNullDirection::Forward {
                    "forward"
                } else {
                    "backward"
                };
                let limit = limit.map_or("None".to_string(), |value| value.to_string());
                let expressions = columns
                    .iter()
                    .map(|column| {
                        format!(
                            "pl.col({}).fill_null(strategy={strategy:?}, limit={limit})",
                            code_quote(column)
                        )
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                lines.push(
                    "    # Requires an earlier stable sort on the canonical time column."
                        .to_string(),
                );
                lines.push(format!("    lf = lf.with_columns([{expressions}])"));
            }
            CleaningStageDto::Resample {
                every,
                aggregations,
                ..
            } => {
                let aggregations = aggregations
                    .iter()
                    .map(|aggregation| {
                        let method = match aggregation.method {
                            ResampleAggregationMethod::Mean => "mean",
                            ResampleAggregationMethod::Sum => "sum",
                            ResampleAggregationMethod::Min => "min",
                            ResampleAggregationMethod::Max => "max",
                            ResampleAggregationMethod::Last => "last",
                        };
                        format!(
                            "pl.col({}).{}().alias({})",
                            code_quote(&aggregation.column),
                            method,
                            code_quote(&aggregation.column)
                        )
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                lines.push(
                    "    # Global fixed-duration buckets; empty buckets are not synthesized."
                        .to_string(),
                );
                lines.push(format!("    lf = lf.group_by_dynamic({}, every={}, period={}, closed=\"left\", label=\"left\", start_by=\"window\").agg([{aggregations}])", code_quote(&plan.time_column), code_quote(every), code_quote(every)));
            }
            CleaningStageDto::ChronologicalSplit {
                train_end_ms,
                validation_end_ms,
                embargo_ms,
                output_column,
                ..
            } => {
                let time = code_quote(&plan.time_column);
                let [
                    train_end,
                    train_embargo_end,
                    validation_end,
                    validation_embargo_end,
                ] = split_native_boundaries(
                    *train_end_ms,
                    *validation_end_ms,
                    *embargo_ms,
                    time_dtype,
                )?;
                lines.push(
                    "    # Compare physical Int64 time values using the source column's native unit."
                        .to_string(),
                );
                lines.push(format!("    lf = lf.with_columns(pl.when(pl.col({time}).cast(pl.Int64).is_null()).then(pl.lit(\"unassigned\")).when(pl.col({time}).cast(pl.Int64) <= {train_end}).then(pl.lit(\"train\")).when(pl.col({time}).cast(pl.Int64) <= {train_embargo_end}).then(pl.lit(\"embargo\")).when(pl.col({time}).cast(pl.Int64) <= {validation_end}).then(pl.lit(\"validation\")).when(pl.col({time}).cast(pl.Int64) <= {validation_embargo_end}).then(pl.lit(\"embargo\")).otherwise(pl.lit(\"test\")).alias({}))", code_quote(output_column)));
            }
            CleaningStageDto::DerivedColumn {
                expression,
                output_column,
                ..
            } => {
                let expression = parse_derived_expression(expression)?;
                lines.push(format!(
                    "    lf = lf.with_columns({}.alias({}))",
                    expression.to_python_polars(),
                    code_quote(output_column)
                ));
            }
            CleaningStageDto::AdaptiveLine { .. } => {
                unreachable!("validated codegen support")
            }
            CleaningStageDto::Annotation { .. } => {}
        }
    }
    lines.push(if executable {
        "    return lf".to_string()
    } else {
        "    return lf  # no enabled executable stages".to_string()
    });
    Ok(format!("{}\n", lines.join("\n")))
}

fn generate_rust_polars(
    plan: &CleaningPlanDto,
    version: &DatasetVersionRecord,
    hash: &str,
    time_dtype: &DataType,
) -> Result<String, AppError> {
    let mut lines = vec![
        "// EdaTime backend-generated canonical plan artifact (v1).".to_string(),
        format!(
            "// source version: {} @ revision {}",
            version.id, version.revision
        ),
        format!("// plan hash: {hash}"),
        "use polars::prelude::*;".to_string(),
        String::new(),
        "pub fn apply_edatime_plan(mut lf: LazyFrame) -> PolarsResult<LazyFrame> {".to_string(),
    ];
    for stage in &plan.stages {
        if !stage.enabled() || matches!(stage, CleaningStageDto::Annotation { .. }) {
            continue;
        }
        match stage {
            CleaningStageDto::TimeRange {
                start_ms,
                end_ms,
                mode,
                ..
            } => {
                let predicate = format!(
                    "col({}).cast(DataType::Float64).gt_eq(lit({})).and(col({}).cast(DataType::Float64).lt_eq(lit({})))",
                    code_quote(&plan.time_column),
                    code_number(start_ms.min(*end_ms)),
                    code_quote(&plan.time_column),
                    code_number(start_ms.max(*end_ms))
                );
                let expression = if *mode == TimeRangeMode::KeepInside {
                    predicate
                } else {
                    format!("{predicate}.is_null().or({predicate}.not())")
                };
                lines.push(format!("    lf = lf.filter({expression});"));
            }
            CleaningStageDto::ColumnRange {
                column,
                from,
                to,
                mode,
                retain_nulls,
                ..
            } => {
                let predicate = format!(
                    "col({}).cast(DataType::Float64).gt_eq(lit({})).and(col({}).cast(DataType::Float64).lt_eq(lit({})))",
                    code_quote(column),
                    code_number(from.min(*to)),
                    code_quote(column),
                    code_number(from.max(*to))
                );
                let expression = if *mode == RangeMode::KeepInside {
                    if *retain_nulls {
                        format!("col({}).is_null().or({predicate})", code_quote(column))
                    } else {
                        predicate
                    }
                } else {
                    format!("{predicate}.is_null().or({predicate}.not())")
                };
                lines.push(format!("    lf = lf.filter({expression});"));
            }
            CleaningStageDto::MissingValue {
                column,
                drop_nulls,
                drop_non_finite,
                ..
            } => {
                let value = format!("col({})", code_quote(column));
                let predicate = match (*drop_nulls, *drop_non_finite) {
                    (true, true) => format!("{value}.is_not_null().and({value}.is_finite())"),
                    (true, false) => format!("{value}.is_not_null()"),
                    (false, true) => format!("{value}.is_null().or({value}.is_finite())"),
                    (false, false) => unreachable!("validated plan"),
                };
                lines.push(format!("    lf = lf.filter({predicate});"));
            }
            CleaningStageDto::Deduplicate { columns, keep, .. } => {
                let columns = columns
                    .iter()
                    .map(|column| format!("col({})", code_quote(column)))
                    .collect::<Vec<_>>()
                    .join(", ");
                let keep = if *keep == DuplicateKeep::First {
                    "First"
                } else {
                    "Last"
                };
                lines.push(format!("    lf = lf.unique_stable_generic(Some(vec![{columns}]), UniqueKeepStrategy::{keep});"));
            }
            CleaningStageDto::ColumnSelect { columns, mode, .. } => {
                let columns = columns
                    .iter()
                    .map(|column| code_quote(column))
                    .collect::<Vec<_>>()
                    .join(", ");
                if *mode == ColumnSelectMode::Keep {
                    lines.push(format!(
                        "    lf = lf.select(vec![{0}]);",
                        columns
                            .split(", ")
                            .map(|column| format!("col({column})"))
                            .collect::<Vec<_>>()
                            .join(", ")
                    ));
                } else {
                    lines.push(format!(
                        "    lf = lf.drop(by_name([{columns}], true, false));"
                    ));
                }
            }
            CleaningStageDto::Sort {
                columns,
                descending,
                nulls_last,
                ..
            } => {
                let columns = columns
                    .iter()
                    .map(|column| code_quote(column))
                    .collect::<Vec<_>>()
                    .join(", ");
                lines.push(format!("    lf = lf.sort(vec![{columns}], SortMultipleOptions::default().with_order_descending({descending}).with_nulls_last({nulls_last}).with_maintain_order(true));"));
            }
            CleaningStageDto::FillNull {
                columns,
                strategy,
                limit,
                ..
            } => {
                let strategy = if *strategy == FillNullDirection::Forward {
                    "Forward"
                } else {
                    "Backward"
                };
                let limit = limit.map_or("None".to_string(), |value| format!("Some({value})"));
                let expressions = columns.iter().map(|column| format!("col({}).fill_null_with_strategy(FillNullStrategy::{strategy}({limit}))", code_quote(column))).collect::<Vec<_>>().join(", ");
                lines.push(format!("    lf = lf.with_columns(vec![{expressions}]);"));
            }
            CleaningStageDto::Resample {
                every,
                aggregations,
                ..
            } => {
                let aggregations = aggregations
                    .iter()
                    .map(|aggregation| {
                        let method = match aggregation.method {
                            ResampleAggregationMethod::Mean => "mean",
                            ResampleAggregationMethod::Sum => "sum",
                            ResampleAggregationMethod::Min => "min",
                            ResampleAggregationMethod::Max => "max",
                            ResampleAggregationMethod::Last => "last",
                        };
                        format!(
                            "col({}).{}().alias({})",
                            code_quote(&aggregation.column),
                            method,
                            code_quote(&aggregation.column)
                        )
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                lines.push(format!(
                    "    let every = Duration::try_parse({})?;",
                    code_quote(every)
                ));
                lines.push(format!("    lf = lf.group_by_dynamic(col({}), [], DynamicGroupOptions {{ every, period: every, offset: Duration::try_parse(\"0ns\")?, closed_window: ClosedWindow::Left, label: Label::Left, start_by: StartBy::WindowBound, ..Default::default() }}).agg([{aggregations}]);", code_quote(&plan.time_column)));
            }
            CleaningStageDto::ChronologicalSplit {
                train_end_ms,
                validation_end_ms,
                embargo_ms,
                output_column,
                ..
            } => {
                let time = code_quote(&plan.time_column);
                let [
                    train_end,
                    train_embargo_end,
                    validation_end,
                    validation_embargo_end,
                ] = split_native_boundaries(
                    *train_end_ms,
                    *validation_end_ms,
                    *embargo_ms,
                    time_dtype,
                )?;
                lines.push("    // Compare physical Int64 time values using the source column's native unit.".to_string());
                lines.push(format!("    lf = lf.with_columns(vec![when(col({time}).cast(DataType::Int64).is_null()).then(lit(\"unassigned\")).when(col({time}).cast(DataType::Int64).lt_eq(lit({train_end}))).then(lit(\"train\")).when(col({time}).cast(DataType::Int64).lt_eq(lit({train_embargo_end}))).then(lit(\"embargo\")).when(col({time}).cast(DataType::Int64).lt_eq(lit({validation_end}))).then(lit(\"validation\")).when(col({time}).cast(DataType::Int64).lt_eq(lit({validation_embargo_end}))).then(lit(\"embargo\")).otherwise(lit(\"test\")).alias({})]);", code_quote(output_column)));
            }
            CleaningStageDto::DerivedColumn {
                expression,
                output_column,
                ..
            } => {
                let expression = parse_derived_expression(expression)?;
                lines.push(format!(
                    "    lf = lf.with_column({}.alias({}));",
                    expression.to_rust_polars(),
                    code_quote(output_column)
                ));
            }
            CleaningStageDto::AdaptiveLine { .. } => {
                unreachable!("validated codegen support")
            }
            CleaningStageDto::Annotation { .. } => {}
        }
    }
    lines.push("    Ok(lf)".to_string());
    lines.push("}".to_string());
    Ok(format!("{}\n", lines.join("\n")))
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CleaningValidationResponse {
    pub source_version: DatasetVersionRecord,
    pub dataset_revision: u64,
    pub plan_hash: String,
    pub canonical_plan: CleaningPlanDto,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CleaningPreviewResponse {
    pub source_version: DatasetVersionRecord,
    pub dataset_revision: u64,
    pub plan_hash: String,
    pub rows_before: usize,
    pub rows_after: usize,
    pub rows_removed: usize,
    pub columns_before: usize,
    pub columns_after: usize,
    pub stage_impacts: Vec<CleaningStageImpact>,
    pub warnings: Vec<String>,
}

/// Exact row-membership change at each saved plan stage. These values are
/// calculated only for an explicit preview request; regular chart queries do
/// not pay for the per-stage collections required to produce this audit view.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CleaningStageImpact {
    pub stage_id: String,
    pub executed: bool,
    pub rows_before: usize,
    pub rows_after: usize,
    pub rows_removed: usize,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CleaningApplyResponse {
    pub job_id: String,
    pub source_version: DatasetVersionRecord,
    pub dataset_revision: u64,
    pub plan_hash: String,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CleaningPlanExportArtifact {
    pub schema_version: u16,
    pub exported_at: DateTime<Utc>,
    pub source_version: DatasetVersionRecord,
    pub dataset_revision: u64,
    pub dataset_fingerprint: String,
    pub schema_fingerprint: String,
    pub plan_hash: String,
    pub plan: CleaningPlanDto,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DatasetVersionSelectRequest {
    pub version_id: String,
}

fn validate_envelope(
    state: &AppState,
    envelope: &PlanRequestEnvelope,
) -> Result<(DatasetVersionRecord, String), AppError> {
    let version = state
        .dataset_versions
        .record(&envelope.expected_source_version_id)
        .map_err(|_| {
            AppError::stale_plan("Requested cleaning-plan source version is unavailable")
        })?;
    if envelope.plan.source_version_id != version.id
        || envelope.expected_source_version_id != version.id
        || envelope.plan.dataset_revision != version.revision
        || envelope.expected_dataset_revision != version.revision
    {
        return Err(AppError::stale_plan(
            "Cleaning plan baseline no longer matches the requested source version",
        ));
    }
    if envelope.plan.dataset_fingerprint.as_deref() != Some(version.dataset_fingerprint.as_str())
        || envelope.plan.schema_fingerprint != version.schema_fingerprint
    {
        return Err(AppError::stale_plan(
            "Cleaning plan fingerprint no longer matches the requested source version",
        ));
    }
    let hash = semantic_hash(&envelope.plan).map_err(AppError::from)?;
    // A frontend hash is an optimistic scheduling hint. The backend hash is
    // authoritative and deliberately returned instead of being trusted here.
    let _ = &envelope.expected_plan_hash;
    Ok((version, hash))
}

fn preview_warnings(plan: &CleaningPlanDto) -> Vec<String> {
    let Some(split_index) = plan.stages.iter().position(|stage| {
        stage.enabled() && matches!(stage, CleaningStageDto::ChronologicalSplit { .. })
    }) else {
        return Vec::new();
    };
    plan.stages[..split_index]
        .iter()
        .filter(|stage| stage.enabled())
        .filter_map(|stage| match stage {
            CleaningStageDto::FillNull { .. } => Some(format!(
                "Potential leakage: ordered null fill stage '{}' runs before the chronological split and can carry values across split boundaries.",
                stage.id()
            )),
            CleaningStageDto::Resample { .. } => Some(format!(
                "Potential leakage: resampling stage '{}' runs before the chronological split and can aggregate values across split boundaries.",
                stage.id()
            )),
            _ => None,
        })
        .collect()
}

pub(crate) fn compile_request_frame(
    state: &AppState,
    envelope: &PlanRequestEnvelope,
) -> Result<(DatasetVersionRecord, String, polars::prelude::LazyFrame), AppError> {
    let (version, plan_hash) = validate_envelope(state, envelope)?;
    let source = state.dataset_snapshot_for_version(&version.id)?;
    let frame = compile_cleaning_plan(source, &envelope.plan).map_err(AppError::from)?;
    Ok((version, plan_hash, frame))
}

pub async fn validate(
    State(state): State<AppState>,
    Json(envelope): Json<PlanRequestEnvelope>,
) -> Result<Json<CleaningValidationResponse>, AppError> {
    let (version, plan_hash, _frame) = compile_request_frame(&state, &envelope)?;
    Ok(Json(CleaningValidationResponse {
        dataset_revision: version.revision,
        source_version: version,
        plan_hash,
        canonical_plan: envelope.plan,
    }))
}

pub async fn preview(
    State(state): State<AppState>,
    Json(envelope): Json<PlanRequestEnvelope>,
) -> Result<Json<CleaningPreviewResponse>, AppError> {
    let (version, plan_hash, frame) = compile_request_frame(&state, &envelope)?;
    let source = state.dataset_snapshot_for_version(&version.id)?;
    let source_schema = source.clone().collect_schema().map_err(|error| {
        AppError::bad_request(format!("Cleaning source schema unavailable: {error}"))
    })?;
    let rows_before = state
        .query_executor
        .execute_async(source.clone())
        .await
        .map_err(AppError::from)?
        .height();
    let mut stage_frame = source.clone();
    let mut prior_rows = rows_before;
    let mut stage_impacts = Vec::with_capacity(envelope.plan.stages.len());
    for stage in &envelope.plan.stages {
        let executed = stage.enabled() && !matches!(stage, CleaningStageDto::Annotation { .. });
        let rows_after = if executed {
            // Compile exactly one stage at a time over the preceding stage's
            // lazy frame. This preserves saved order and exposes the real
            // marginal effect instead of independently comparing every stage
            // against the raw source.
            let one_stage_plan = CleaningPlanDto {
                stages: vec![stage.clone()],
                ..envelope.plan.clone()
            };
            stage_frame =
                compile_cleaning_plan(stage_frame, &one_stage_plan).map_err(AppError::from)?;
            state
                .query_executor
                .execute_async(stage_frame.clone())
                .await
                .map_err(AppError::from)?
                .height()
        } else {
            prior_rows
        };
        stage_impacts.push(CleaningStageImpact {
            stage_id: stage.id().to_string(),
            executed,
            rows_before: prior_rows,
            rows_after,
            rows_removed: prior_rows.saturating_sub(rows_after),
        });
        prior_rows = rows_after;
    }
    let result = state
        .query_executor
        .execute_async(frame)
        .await
        .map_err(AppError::from)?;
    let rows_after = result.height();
    Ok(Json(CleaningPreviewResponse {
        dataset_revision: version.revision,
        source_version: version,
        plan_hash,
        rows_before,
        rows_after,
        rows_removed: rows_before.saturating_sub(rows_after),
        columns_before: source_schema.len(),
        columns_after: result.width(),
        stage_impacts,
        warnings: preview_warnings(&envelope.plan),
    }))
}

/// Calculate global z-score or IQR outlier bounds over the current canonical
/// working frame. This is intentionally a proposal: it never writes a dataset
/// and lets the client add the returned ranges to its editable plan.
pub async fn propose_outliers(
    State(state): State<AppState>,
    Json(request): Json<OutlierProposalRequest>,
) -> Result<Json<OutlierProposalResponse>, AppError> {
    let method = request.method.trim().to_ascii_lowercase();
    if !matches!(method.as_str(), "zscore" | "iqr") {
        return Err(AppError::bad_request(
            "Outlier proposal method must be zscore or iqr",
        ));
    }
    if !request.threshold.is_finite() || request.threshold <= 0.0 {
        return Err(AppError::bad_request(
            "Outlier proposal threshold must be finite and positive",
        ));
    }
    let columns = request
        .columns
        .iter()
        .map(|column| column.trim())
        .filter(|column| !column.is_empty())
        .map(str::to_string)
        .collect::<Vec<_>>();
    if columns.is_empty()
        || columns.len()
            != columns
                .iter()
                .collect::<std::collections::HashSet<_>>()
                .len()
    {
        return Err(AppError::bad_request(
            "Outlier proposal requires unique non-empty numeric columns",
        ));
    }
    let (version, plan_hash, frame) = compile_request_frame(&state, &request.context)?;
    let schema = frame.clone().collect_schema().map_err(|error| {
        AppError::bad_request(format!(
            "Failed to inspect outlier proposal columns: {error}"
        ))
    })?;
    for column in &columns {
        if !schema.get(column).is_some_and(|dtype| dtype.is_numeric()) {
            return Err(AppError::bad_request(format!(
                "Outlier proposal column '{column}' must be numeric"
            )));
        }
    }
    let data = state
        .query_executor
        .execute_async(frame)
        .await
        .map_err(AppError::from)?;
    let mut ranges = Vec::new();
    for column in columns {
        let values = data
            .column(&column)
            .map_err(|error| {
                AppError::internal(format!(
                    "Outlier proposal column '{column}' is unavailable: {error}"
                ))
            })?
            .as_materialized_series()
            .cast(&DataType::Float64)
            .map_err(|error| {
                AppError::internal(format!(
                    "Outlier proposal could not cast '{column}': {error}"
                ))
            })?
            .f64()
            .map_err(|error| {
                AppError::internal(format!(
                    "Outlier proposal could not read '{column}': {error}"
                ))
            })?
            .into_iter()
            .flatten()
            .filter(|value| value.is_finite())
            .collect::<Vec<_>>();
        let bounds = if method == "iqr" {
            let stats = edatime_core::stats::compute_column_stats(&values);
            match (stats.q1, stats.q3) {
                (Some(q1), Some(q3)) => {
                    let iqr = q3 - q1;
                    Some((q1 - request.threshold * iqr, q3 + request.threshold * iqr))
                }
                _ => None,
            }
        } else if values.len() < 2 {
            None
        } else {
            let n = values.len() as f64;
            let mean = values.iter().sum::<f64>() / n;
            let std = (values
                .iter()
                .map(|value| (value - mean).powi(2))
                .sum::<f64>()
                / n)
                .sqrt();
            (std >= f64::EPSILON).then_some((
                mean - request.threshold * std,
                mean + request.threshold * std,
            ))
        };
        if let Some((from, to)) = bounds {
            ranges.push(OutlierRangeProposal {
                column,
                from,
                to,
                retain_nulls: true,
            });
        }
    }
    Ok(Json(OutlierProposalResponse {
        source_version: version.clone(),
        dataset_revision: version.revision,
        plan_hash,
        method,
        threshold: request.threshold,
        ranges,
    }))
}

pub async fn export_data(
    State(state): State<AppState>,
    Json(request): Json<CleaningDataExportRequest>,
) -> Result<Response, AppError> {
    if request.format != "parquet" {
        return Err(AppError::bad_request(
            "Cleaning data export currently supports format 'parquet' only",
        ));
    }
    let (version, plan_hash, mut frame) = compile_request_frame(&state, &request.context)?;
    if let Some(columns) = request.output_columns.as_ref() {
        if columns.is_empty() {
            return Err(AppError::bad_request(
                "Cleaning export outputColumns must not be empty when supplied",
            ));
        }
        frame = frame.select(columns.iter().map(polars::prelude::col).collect::<Vec<_>>());
    }
    let response =
        lazy_parquet_response(&state.query_executor, frame, "edatime_cleaned.parquet").await?;
    Ok(add_execution_identity_headers(
        response,
        &ExecutionIdentity::from_version(version, Some(plan_hash)),
    ))
}

/// Export the backend-validated canonical plan together with the immutable
/// source identity that the data export is bound to.
pub async fn export_plan(
    State(state): State<AppState>,
    Json(envelope): Json<PlanRequestEnvelope>,
) -> Result<Response, AppError> {
    let (version, plan_hash) = validate_envelope(&state, &envelope)?;
    // Compile once here as well: plan export must not claim executability for
    // a stage that only passed envelope identity validation.
    let source = state.dataset_snapshot_for_version(&version.id)?;
    let _ = compile_cleaning_plan(source, &envelope.plan).map_err(AppError::from)?;
    let artifact = CleaningPlanExportArtifact {
        schema_version: 1,
        exported_at: Utc::now(),
        dataset_revision: version.revision,
        dataset_fingerprint: version.dataset_fingerprint.clone(),
        schema_fingerprint: version.schema_fingerprint.clone(),
        source_version: version,
        plan_hash,
        plan: envelope.plan,
    };
    let bytes = serde_json::to_vec_pretty(&artifact).map_err(|error| {
        AppError::internal(format!("Cleaning plan serialization failed: {error}"))
    })?;
    let mut response = Response::new(bytes.into());
    response.headers_mut().insert(
        header::CONTENT_TYPE,
        HeaderValue::from_static("application/json; charset=utf-8"),
    );
    response.headers_mut().insert(
        header::CONTENT_DISPOSITION,
        HeaderValue::from_static("attachment; filename=edatime_cleaning_plan.json"),
    );
    Ok(add_execution_identity_headers(
        response,
        &ExecutionIdentity::from_version(artifact.source_version, Some(artifact.plan_hash)),
    ))
}

fn manifest_summary(data: &polars::prelude::DataFrame) -> Result<ManifestDatasetSummary, AppError> {
    let metadata = crate::handlers::routes::metadata::build_dataset_metadata(data, false, None)?;
    Ok(ManifestDatasetSummary {
        rows: metadata.total_rows,
        columns: metadata.columns.len(),
        time_range: metadata.time_range,
        null_count: metadata
            .column_profiles
            .iter()
            .map(|profile| profile.null_count)
            .sum(),
        non_finite_count: metadata
            .column_profiles
            .iter()
            .map(|profile| profile.non_finite_count)
            .sum(),
    })
}

async fn build_handoff_manifest(
    state: &AppState,
    envelope: &PlanRequestEnvelope,
) -> Result<(DatasetVersionRecord, String, CleaningHandoffManifest), AppError> {
    let (version, plan_hash, frame) = compile_request_frame(state, envelope)?;
    let root_version = state
        .dataset_versions()?
        .into_iter()
        .find(|candidate| candidate.id == version.root_id)
        .ok_or_else(|| AppError::internal("Cleaning manifest root source is unavailable"))?;
    let source = state.dataset_snapshot_for_version(&version.id)?;
    let (before, after) = tokio::try_join!(
        state.query_executor.execute_async(source),
        state.query_executor.execute_async(frame),
    )
    .map_err(AppError::from)?;
    let manifest = CleaningHandoffManifest {
        schema_version: 1,
        exported_at: Utc::now(),
        execution_provenance: ManifestExecutionProvenance {
            application: "edatime-service",
            application_version: env!("CARGO_PKG_VERSION"),
            plan_schema_version: envelope.plan.schema_version,
            semantic_hash_algorithm: "fnv1a-v1",
            execution_mode: "exact-plan-v1",
        },
        source_version: version.clone(),
        root_source_version: root_version,
        plan_hash: plan_hash.clone(),
        canonical_plan: envelope.plan.clone(),
        before: manifest_summary(&before)?,
        after: manifest_summary(&after)?,
        artifact_checksums: ManifestArtifactChecksums {
            source_dataset: version.dataset_fingerprint.clone(),
            source_schema: version.schema_fingerprint.clone(),
            canonical_plan: plan_hash.clone(),
        },
    };
    Ok((version, plan_hash, manifest))
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct CleaningBundleChecksums {
    schema_version: u16,
    algorithm: &'static str,
    artifacts: BTreeMap<String, String>,
}

fn sha256_hex(bytes: &[u8]) -> String {
    format!("sha256:{:x}", Sha256::digest(bytes))
}

/// Bundle independently usable, backend-generated handoff artifacts without
/// making browser code responsible for provenance or source generation.
fn build_handoff_bundle(mut artifacts: Vec<(String, Vec<u8>)>) -> Result<Vec<u8>, AppError> {
    let checksums = artifacts
        .iter()
        .map(|(name, bytes)| (name.clone(), sha256_hex(bytes)))
        .collect::<BTreeMap<_, _>>();
    let index = CleaningBundleChecksums {
        schema_version: 1,
        algorithm: "sha256",
        artifacts: checksums,
    };
    artifacts.push((
        "checksums.json".to_string(),
        serde_json::to_vec_pretty(&index).map_err(|error| {
            AppError::internal(format!("Bundle checksum serialization failed: {error}"))
        })?,
    ));
    let mut archive = ZipWriter::new(Cursor::new(Vec::new()));
    let options = FileOptions::default().compression_method(CompressionMethod::Stored);
    for (name, bytes) in artifacts {
        archive.start_file(name, options).map_err(|error| {
            AppError::internal(format!("Bundle archive creation failed: {error}"))
        })?;
        archive
            .write_all(&bytes)
            .map_err(|error| AppError::internal(format!("Bundle archive write failed: {error}")))?;
    }
    archive
        .finish()
        .map(|cursor| cursor.into_inner())
        .map_err(|error| AppError::internal(format!("Bundle archive finalization failed: {error}")))
}

/// Export an exact, source-bound reproducibility manifest for the compiled
/// plan. Unlike interactive chart queries this intentionally collects both
/// sides so row/column and quality summaries are audit facts, not estimates.
pub async fn export_manifest(
    State(state): State<AppState>,
    Json(envelope): Json<PlanRequestEnvelope>,
) -> Result<Response, AppError> {
    let (version, plan_hash, manifest) = build_handoff_manifest(&state, &envelope).await?;
    let bytes = serde_json::to_vec_pretty(&manifest)
        .map_err(|error| AppError::internal(format!("Manifest serialization failed: {error}")))?;
    let mut response = Response::new(bytes.into());
    response.headers_mut().insert(
        header::CONTENT_TYPE,
        HeaderValue::from_static("application/json; charset=utf-8"),
    );
    response.headers_mut().insert(
        header::CONTENT_DISPOSITION,
        HeaderValue::from_static("attachment; filename=edatime_handoff_manifest.json"),
    );
    Ok(add_execution_identity_headers(
        response,
        &ExecutionIdentity::from_version(version, Some(plan_hash)),
    ))
}

/// Export a complete, source-bound handoff archive. Every executable artifact
/// is generated after canonical validation, and `checksums.json` records the
/// SHA-256 digest of every other archive member.
pub async fn export_bundle(
    State(state): State<AppState>,
    Json(envelope): Json<PlanRequestEnvelope>,
) -> Result<Response, AppError> {
    let (version, plan_hash, manifest) = build_handoff_manifest(&state, &envelope).await?;
    validate_codegen_support(&envelope.plan)?;
    let source_schema = state
        .dataset_snapshot_for_version(&version.id)?
        .collect_schema()
        .map_err(|error| {
            AppError::bad_request(format!(
                "Failed to inspect bundle code-export time column: {error}"
            ))
        })?;
    let time_dtype = source_schema
        .get(&envelope.plan.time_column)
        .ok_or_else(|| {
            AppError::bad_request(format!(
                "Missing time column '{}' for bundle code export",
                envelope.plan.time_column
            ))
        })?;
    let artifacts = vec![
        (
            "handoff-manifest.json".to_string(),
            serde_json::to_vec_pretty(&manifest).map_err(|error| {
                AppError::internal(format!("Bundle manifest serialization failed: {error}"))
            })?,
        ),
        (
            "canonical-plan.json".to_string(),
            serde_json::to_vec_pretty(&envelope.plan).map_err(|error| {
                AppError::internal(format!("Bundle plan serialization failed: {error}"))
            })?,
        ),
        (
            "apply_edatime_plan.py".to_string(),
            generate_python_polars(&envelope.plan, &version, &plan_hash, time_dtype)?.into_bytes(),
        ),
        (
            "apply_edatime_plan.rs".to_string(),
            generate_rust_polars(&envelope.plan, &version, &plan_hash, time_dtype)?.into_bytes(),
        ),
    ];
    let bytes = build_handoff_bundle(artifacts)?;
    let mut response = Response::new(bytes.into());
    response.headers_mut().insert(
        header::CONTENT_TYPE,
        HeaderValue::from_static("application/zip"),
    );
    response.headers_mut().insert(
        header::CONTENT_DISPOSITION,
        HeaderValue::from_static("attachment; filename=edatime_handoff_bundle.zip"),
    );
    Ok(add_execution_identity_headers(
        response,
        &ExecutionIdentity::from_version(version, Some(plan_hash)),
    ))
}

/// Export v1 Python or Rust application code generated by the same backend
/// that validates and compiles the canonical plan.
pub async fn export_code(
    State(state): State<AppState>,
    Json(request): Json<CleaningCodeExportRequest>,
) -> Result<Response, AppError> {
    let (version, plan_hash, _frame) = compile_request_frame(&state, &request.context)?;
    validate_codegen_support(&request.context.plan)?;
    let source_schema = state
        .dataset_snapshot_for_version(&version.id)?
        .collect_schema()
        .map_err(|error| {
            AppError::bad_request(format!(
                "Failed to inspect code-export time column: {error}"
            ))
        })?;
    let time_dtype = source_schema
        .get(&request.context.plan.time_column)
        .ok_or_else(|| {
            AppError::bad_request(format!(
                "Missing time column '{}' for code export",
                request.context.plan.time_column
            ))
        })?;
    let (content, disposition, content_type) = match request.language {
        CleaningCodeLanguage::Python => (
            generate_python_polars(&request.context.plan, &version, &plan_hash, time_dtype)?,
            "attachment; filename=apply_edatime_plan.py",
            "text/x-python; charset=utf-8",
        ),
        CleaningCodeLanguage::Rust => (
            generate_rust_polars(&request.context.plan, &version, &plan_hash, time_dtype)?,
            "attachment; filename=apply_edatime_plan.rs",
            "text/rust; charset=utf-8",
        ),
    };
    let mut response = Response::new(content.into());
    response
        .headers_mut()
        .insert(header::CONTENT_TYPE, HeaderValue::from_static(content_type));
    response.headers_mut().insert(
        header::CONTENT_DISPOSITION,
        HeaderValue::from_static(disposition),
    );
    Ok(add_execution_identity_headers(
        response,
        &ExecutionIdentity::from_version(version, Some(plan_hash)),
    ))
}

/// Explicitly materialize the compiled plan as a new child source version.
/// Export and preview never call this route, so the immutable baseline stays
/// available until the user deliberately chooses this transition.
pub async fn apply(
    State(state): State<AppState>,
    Json(envelope): Json<PlanRequestEnvelope>,
) -> Result<Response, AppError> {
    let (version, plan_hash, frame) = compile_request_frame(&state, &envelope)?;
    let job = state.jobs.create_with_request_id(
        JobKind::Materialization,
        crate::middleware::current_request_id(),
    );
    if !state.jobs.start(&job) {
        return Err(AppError::internal(
            "Could not start plan materialization job",
        ));
    }
    state.jobs.update_progress(
        &job,
        10,
        Some("materializing canonical cleaning plan".to_string()),
    );
    let result = if state.artifact_store.is_some() {
        state
            .materialize_dataset_child_lazy(
                &version.id,
                frame,
                plan_hash.clone(),
                envelope.plan.time_column.clone(),
                Some(&job),
            )
            .await
    } else {
        async {
            if job.is_cancelled() {
                return Err(edatime_core::error::AppError::bad_request(
                    "Materialization job cancelled before collection",
                ));
            }
            let data = state.query_executor.execute_async(frame).await?;
            if job.is_cancelled() {
                return Err(edatime_core::error::AppError::bad_request(
                    "Materialization job cancelled before publication",
                ));
            }
            state
                .materialize_dataset_child(&version.id, data, plan_hash.clone())
                .await
        }
        .await
    };
    let child = match result {
        Ok(child) => child,
        Err(error) => {
            state.jobs.fail(&job, error.to_string());
            return Err(AppError::from(error));
        }
    };
    state.jobs.complete(&job);
    let response = CleaningApplyResponse {
        job_id: job.id().to_string(),
        dataset_revision: child.revision,
        source_version: child.clone(),
        plan_hash: plan_hash.clone(),
    };
    Ok(add_execution_identity_headers(
        Json(response).into_response(),
        &ExecutionIdentity::from_version(child, Some(plan_hash)),
    ))
}

pub async fn list_versions(
    State(state): State<AppState>,
) -> Result<Json<Vec<DatasetVersionRecord>>, AppError> {
    Ok(Json(state.dataset_versions()?))
}

pub async fn get_storage_usage(
    State(state): State<AppState>,
) -> Result<Json<ArtifactStorageUsage>, AppError> {
    Ok(Json(state.artifact_storage_usage()?))
}

/// Explicitly select a retained version. Preview and export never change the
/// active dataset, so the original remains recoverable by user action.
pub async fn select_version(
    State(state): State<AppState>,
    Json(request): Json<DatasetVersionSelectRequest>,
) -> Result<Json<DatasetVersionRecord>, AppError> {
    let id = request.version_id.trim();
    if id.is_empty() {
        return Err(AppError::bad_request("versionId must not be empty"));
    }
    Ok(Json(state.select_dataset_version(id).await?))
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::extract::State;
    use edatime_core::config::AppConfig;
    use edatime_query::cleaning::{CleaningStageBaseDto, CleaningStageDto, RangeMode};
    use polars::prelude::{DataFrame, NamedFrom, ParquetReader, SerReader, Series};
    use std::fs;
    use std::io::Read;

    fn state() -> AppState {
        let df = DataFrame::new(
            3,
            vec![
                Series::new("ts".into(), vec![1_i64, 2, 3]).into(),
                Series::new("value".into(), vec![1.0_f64, 2.0, 3.0]).into(),
            ],
        )
        .expect("frame");
        AppState::new(df, AppConfig::default())
    }

    fn base(id: &str) -> CleaningStageBaseDto {
        CleaningStageBaseDto {
            id: id.to_string(),
            enabled: true,
            execution_class: "polarsExpression".to_string(),
            scope: "row".to_string(),
            source_page: "timeseries".to_string(),
            label: id.to_string(),
            note: None,
            created_at: "now".to_string(),
            updated_at: "now".to_string(),
        }
    }

    fn envelope(state: &AppState) -> PlanRequestEnvelope {
        let version = state.current_dataset_version().expect("version");
        PlanRequestEnvelope {
            expected_plan_hash: None,
            expected_source_version_id: version.id.clone(),
            expected_dataset_revision: version.revision,
            plan: CleaningPlanDto {
                schema_version: 1,
                id: "plan".to_string(),
                plan_revision: 1,
                source_version_id: version.id,
                dataset_revision: version.revision,
                dataset_fingerprint: Some(version.dataset_fingerprint),
                schema_fingerprint: version.schema_fingerprint,
                time_column: "ts".to_string(),
                source_name: None,
                stages: vec![CleaningStageDto::ColumnRange {
                    base: base("range"),
                    column: "value".to_string(),
                    from: 2.0,
                    to: 3.0,
                    mode: RangeMode::KeepInside,
                    retain_nulls: false,
                }],
                created_at: "now".to_string(),
                updated_at: "now".to_string(),
            },
        }
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn preview_and_export_use_the_requested_immutable_baseline() {
        let state = state();
        let response = preview(State(state.clone()), Json(envelope(&state)))
            .await
            .expect("preview")
            .0;
        assert_eq!(response.rows_before, 3);
        assert_eq!(response.rows_after, 2);
        assert_eq!(response.stage_impacts.len(), 1);
        assert_eq!(response.stage_impacts[0].stage_id, "range");
        assert!(response.stage_impacts[0].executed);
        assert_eq!(response.stage_impacts[0].rows_before, 3);
        assert_eq!(response.stage_impacts[0].rows_after, 2);
        assert_eq!(response.stage_impacts[0].rows_removed, 1);

        let export = export_data(
            State(state.clone()),
            Json(CleaningDataExportRequest {
                context: envelope(&state),
                format: "parquet".to_string(),
                output_columns: None,
            }),
        )
        .await
        .expect("export");
        assert_eq!(
            export
                .headers()
                .get("x-edatime-source-version")
                .expect("source version"),
            "source-0"
        );
        assert!(export.headers().get("x-edatime-plan-hash").is_some());
        assert!(
            export
                .headers()
                .get("x-edatime-schema-fingerprint")
                .is_some()
        );
        let advertised_size = export
            .headers()
            .get(header::CONTENT_LENGTH)
            .and_then(|value| value.to_str().ok())
            .and_then(|value| value.parse::<usize>().ok())
            .expect("content length");
        let body = axum::body::to_bytes(export.into_body(), usize::MAX)
            .await
            .expect("streamed export body");
        assert_eq!(body.len(), advertised_size);
        let data = ParquetReader::new(std::io::Cursor::new(body))
            .finish()
            .expect("streamed parquet");
        assert_eq!(data.height(), 2);
        assert_eq!(
            data.column("value")
                .expect("value")
                .f64()
                .expect("f64")
                .into_no_null_iter()
                .collect::<Vec<_>>(),
            vec![2.0, 3.0]
        );
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn outlier_proposal_returns_plan_aware_non_destructive_bounds() {
        let state = state();
        let response = propose_outliers(
            State(state.clone()),
            Json(OutlierProposalRequest {
                context: envelope(&state),
                columns: vec!["value".to_string()],
                method: "zscore".to_string(),
                threshold: 1.0,
            }),
        )
        .await
        .expect("proposal")
        .0;
        assert_eq!(response.source_version.id, "source-0");
        assert_eq!(response.method, "zscore");
        assert_eq!(response.ranges.len(), 1);
        assert_eq!(response.ranges[0].column, "value");
        assert!(response.ranges[0].retain_nulls);
        // The fixture's canonical plan already keeps value in [2, 3], so
        // the proposal proves it measures the working frame, not raw data.
        assert!((response.ranges[0].from - 2.0).abs() < 0.001);
        assert!((response.ranges[0].to - 3.0).abs() < 0.001);
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn stale_source_identity_is_rejected_before_execution() {
        let state = state();
        let mut request = envelope(&state);
        request.expected_source_version_id = "missing".to_string();
        let error = validate(State(state), Json(request))
            .await
            .expect_err("stale source");
        assert_eq!(error.code, crate::error::ErrorCode::StalePlan);
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn apply_creates_a_child_without_losing_the_requested_baseline() {
        let state = state();
        let root = state.current_dataset_version().expect("root");
        let response = apply(State(state.clone()), Json(envelope(&state)))
            .await
            .expect("apply");
        assert_eq!(
            response
                .headers()
                .get("x-edatime-source-version")
                .and_then(|value| value.to_str().ok()),
            Some("source-1")
        );
        let body = axum::body::to_bytes(response.into_body(), usize::MAX)
            .await
            .expect("response body");
        let response: serde_json::Value = serde_json::from_slice(&body).expect("response JSON");
        let job_id = response["jobId"].as_str().expect("materialization job id");
        assert_eq!(
            state.jobs.record(job_id).expect("job record").status,
            edatime_store::jobs::JobStatus::Completed
        );
        assert_eq!(
            response["sourceVersion"]["parentId"].as_str(),
            Some(root.id.as_str())
        );
        assert_eq!(
            state
                .dataset_snapshot_for_version(&root.id)
                .expect("root")
                .collect()
                .expect("collect")
                .height(),
            3
        );
        assert_eq!(
            state
                .dataset_snapshot()
                .collect()
                .expect("working")
                .height(),
            2
        );
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn configured_apply_streams_to_a_scan_backed_child_artifact() {
        let artifact_dir = std::env::temp_dir().join(format!(
            "edatime-cleaning-lazy-apply-{}",
            Utc::now().timestamp_nanos_opt().unwrap_or_default()
        ));
        let mut config = AppConfig::default();
        config.data.artifact_dir = Some(artifact_dir.clone());
        let df = DataFrame::new(
            3,
            vec![
                Series::new("ts".into(), vec![1_i64, 2, 3]).into(),
                Series::new("value".into(), vec![1.0_f64, 2.0, 3.0]).into(),
            ],
        )
        .expect("frame");
        let state = AppState::new(df, config);

        let response = apply(State(state.clone()), Json(envelope(&state)))
            .await
            .expect("streaming apply");

        assert_eq!(response.status(), axum::http::StatusCode::OK);
        let child = state.current_dataset_version().expect("child");
        assert!(child.id.starts_with("artifact-"));
        assert!(child.dataset_fingerprint.starts_with("fnv1a-parquet-"));
        assert_eq!(state.dataset_rows().await, 2);
        assert_eq!(
            state
                .query_executor
                .execute_async(state.dataset_snapshot())
                .await
                .expect("scan child")
                .height(),
            2
        );
        let catalog = state
            .artifact_store
            .as_ref()
            .expect("artifact store")
            .load_catalog()
            .expect("catalog");
        assert_eq!(catalog.len(), 1);
        assert_eq!(catalog[0].version_id, child.id);
        assert!(
            !artifact_dir
                .join(format!("{}.parquet.tmp", child.id))
                .exists()
        );
        fs::remove_dir_all(artifact_dir).expect("clean artifact directory");
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn plan_export_carries_the_same_immutable_identity_as_execution() {
        let state = state();
        let export = export_plan(State(state.clone()), Json(envelope(&state)))
            .await
            .expect("export");
        assert_eq!(
            export.headers().get(header::CONTENT_TYPE).expect("type"),
            "application/json; charset=utf-8"
        );
        let body = axum::body::to_bytes(export.into_body(), usize::MAX)
            .await
            .expect("body");
        let artifact: serde_json::Value = serde_json::from_slice(&body).expect("json");
        assert_eq!(artifact["sourceVersion"]["id"], "source-0");
        assert!(artifact["planHash"].as_str().is_some());
        assert_eq!(artifact["plan"]["sourceVersionId"], "source-0");
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn code_export_is_backend_validated_and_source_bound() {
        let state = state();
        let export = export_code(
            State(state.clone()),
            Json(CleaningCodeExportRequest {
                context: envelope(&state),
                language: CleaningCodeLanguage::Python,
            }),
        )
        .await
        .expect("export");
        assert_eq!(
            export.headers().get(header::CONTENT_TYPE).expect("type"),
            "text/x-python; charset=utf-8"
        );
        assert_eq!(
            export
                .headers()
                .get("x-edatime-source-version")
                .expect("source"),
            "source-0"
        );
        let body = axum::body::to_bytes(export.into_body(), usize::MAX)
            .await
            .expect("body");
        let code = String::from_utf8(body.to_vec()).expect("utf8");
        assert!(code.contains("EdaTime backend-generated canonical plan artifact"));
        assert!(code.contains("pl.col(\"value\")"));
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn code_export_supports_chronological_split_labels() {
        let state = state();
        let mut context = envelope(&state);
        context.plan.stages = vec![CleaningStageDto::ChronologicalSplit {
            base: base("split"),
            train_end_ms: 1.0,
            validation_end_ms: 2.0,
            embargo_ms: 0.0,
            output_column: "split".to_string(),
        }];
        let export = export_code(
            State(state),
            Json(CleaningCodeExportRequest {
                context,
                language: CleaningCodeLanguage::Python,
            }),
        )
        .await
        .expect("export");
        let body = axum::body::to_bytes(export.into_body(), usize::MAX)
            .await
            .expect("body");
        let code = String::from_utf8(body.to_vec()).expect("utf8");
        assert!(code.contains("unassigned"));
        assert!(code.contains("validation"));
        assert!(code.contains("cast(pl.Int64)"));
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn code_export_supports_canonical_derived_columns() {
        let state = state();
        let mut context = envelope(&state);
        context.plan.stages = vec![CleaningStageDto::DerivedColumn {
            base: base("derived"),
            expression: "sqrt(value) + 1".to_string(),
            output_column: "score".to_string(),
        }];
        let export = export_code(
            State(state),
            Json(CleaningCodeExportRequest {
                context,
                language: CleaningCodeLanguage::Python,
            }),
        )
        .await
        .expect("export");
        let body = axum::body::to_bytes(export.into_body(), usize::MAX)
            .await
            .expect("body");
        let code = String::from_utf8(body.to_vec()).expect("utf8");
        assert!(code.contains("pl.col(\"value\")"));
        assert!(code.contains("alias(\"score\")"));
    }

    #[test]
    fn codegen_split_uses_native_date_boundaries() {
        let state = state();
        let mut context = envelope(&state);
        context.plan.stages = vec![CleaningStageDto::ChronologicalSplit {
            base: base("split"),
            train_end_ms: 86_400_000.0,
            validation_end_ms: 172_800_000.0,
            embargo_ms: 0.0,
            output_column: "split".to_string(),
        }];
        let version = state.current_dataset_version().expect("version");
        let python = generate_python_polars(&context.plan, &version, "hash", &DataType::Date)
            .expect("python code");
        let rust = generate_rust_polars(&context.plan, &version, "hash", &DataType::Date)
            .expect("rust code");
        assert!(python.contains("cast(pl.Int64) <= 1"));
        assert!(python.contains("cast(pl.Int64) <= 2"));
        assert!(rust.contains("cast(DataType::Int64).lt_eq(lit(1))"));
        assert!(rust.contains("cast(DataType::Int64).lt_eq(lit(2))"));
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn handoff_manifest_binds_exact_before_after_and_checksums() {
        let state = state();
        let export = export_manifest(State(state.clone()), Json(envelope(&state)))
            .await
            .expect("manifest");
        let body = axum::body::to_bytes(export.into_body(), usize::MAX)
            .await
            .expect("body");
        let manifest: serde_json::Value = serde_json::from_slice(&body).expect("json");
        assert_eq!(manifest["sourceVersion"]["id"], "source-0");
        assert_eq!(manifest["rootSourceVersion"]["id"], "source-0");
        assert_eq!(manifest["before"]["rows"], 3);
        assert_eq!(manifest["after"]["rows"], 2);
        assert_eq!(manifest["after"]["columns"], 2);
        assert_eq!(
            manifest["executionProvenance"]["application"],
            "edatime-service"
        );
        assert_eq!(
            manifest["executionProvenance"]["planSchemaVersion"],
            manifest["canonicalPlan"]["schemaVersion"]
        );
        assert_eq!(
            manifest["executionProvenance"]["executionMode"],
            "exact-plan-v1"
        );
        assert_eq!(
            manifest["artifactChecksums"]["canonicalPlan"],
            manifest["planHash"]
        );
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn handoff_bundle_contains_verified_canonical_artifacts() {
        let state = state();
        let export = export_bundle(State(state.clone()), Json(envelope(&state)))
            .await
            .expect("bundle");
        assert_eq!(
            export
                .headers()
                .get(header::CONTENT_TYPE)
                .and_then(|value| value.to_str().ok()),
            Some("application/zip")
        );
        let body = axum::body::to_bytes(export.into_body(), usize::MAX)
            .await
            .expect("body");
        let mut archive = zip::ZipArchive::new(Cursor::new(body.to_vec())).expect("zip archive");
        let names = (0..archive.len())
            .map(|index| {
                archive
                    .by_index(index)
                    .expect("archive entry")
                    .name()
                    .to_string()
            })
            .collect::<Vec<_>>();
        assert_eq!(
            names,
            vec![
                "handoff-manifest.json",
                "canonical-plan.json",
                "apply_edatime_plan.py",
                "apply_edatime_plan.rs",
                "checksums.json",
            ]
        );
        let mut checksums = String::new();
        archive
            .by_name("checksums.json")
            .expect("checksums entry")
            .read_to_string(&mut checksums)
            .expect("checksums text");
        let checksums: serde_json::Value =
            serde_json::from_str(&checksums).expect("checksums json");
        assert_eq!(checksums["algorithm"], "sha256");
        let mut canonical_plan = Vec::new();
        archive
            .by_name("canonical-plan.json")
            .expect("plan entry")
            .read_to_end(&mut canonical_plan)
            .expect("plan bytes");
        assert_eq!(
            checksums["artifacts"]["canonical-plan.json"],
            sha256_hex(&canonical_plan)
        );
    }

    #[test]
    fn preview_warns_when_resampling_precedes_a_chronological_split() {
        let mut request = envelope(&state());
        request.plan.stages = vec![
            CleaningStageDto::Resample {
                base: base("resample"),
                every: "1s".to_string(),
                aggregations: vec![edatime_query::cleaning::ResampleAggregationDto {
                    column: "value".to_string(),
                    method: edatime_query::cleaning::ResampleAggregationMethod::Mean,
                }],
            },
            CleaningStageDto::ChronologicalSplit {
                base: base("split"),
                train_end_ms: 1.0,
                validation_end_ms: 2.0,
                embargo_ms: 0.0,
                output_column: "split".to_string(),
            },
        ];
        assert!(preview_warnings(&request.plan)[0].contains("resample"));
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn selecting_a_retained_root_restores_its_full_working_frame() {
        let state = state();
        let root = state.current_dataset_version().expect("root");
        let _ = apply(State(state.clone()), Json(envelope(&state)))
            .await
            .expect("apply");
        let selected = select_version(
            State(state.clone()),
            Json(DatasetVersionSelectRequest {
                version_id: root.id.clone(),
            }),
        )
        .await
        .expect("select")
        .0;
        assert_eq!(selected.id, root.id);
        assert_eq!(
            state
                .dataset_snapshot()
                .collect()
                .expect("working")
                .height(),
            3
        );
        assert_eq!(
            state.current_dataset_version().expect("current").id,
            root.id
        );
    }
}
