//! Exact source-bound handoff manifests and archive assembly.

use std::{
    collections::BTreeMap,
    io::{Cursor, Write},
};

use chrono::{DateTime, Utc};
use serde::Serialize;
use sha2::{Digest, Sha256};
use zip::{CompressionMethod, ZipWriter, write::FileOptions};

use super::cleaning_context::{PlanRequestEnvelope, resolve_cleaning_context};
use crate::error::AppError;
use edatime_query::cleaning::CleaningPlanDto;
use edatime_store::state::AppState;
use edatime_store::versions::DatasetVersionRecord;

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub(super) struct CleaningHandoffManifest {
    pub schema_version: u16,
    pub exported_at: DateTime<Utc>,
    pub execution_provenance: ManifestExecutionProvenance,
    pub source_version: DatasetVersionRecord,
    pub root_source_version: DatasetVersionRecord,
    pub plan_hash: String,
    pub canonical_plan: CleaningPlanDto,
    pub before: ManifestDatasetSummary,
    pub after: ManifestDatasetSummary,
    pub artifact_checksums: ManifestArtifactChecksums,
}

/// Versioned backend facts needed to reproduce the semantics of a handoff.
/// These are generated by the executing service, never accepted from a client.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub(super) struct ManifestExecutionProvenance {
    pub application: &'static str,
    pub application_version: &'static str,
    pub plan_schema_version: u16,
    pub semantic_hash_algorithm: &'static str,
    pub execution_mode: &'static str,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub(super) struct ManifestDatasetSummary {
    pub rows: usize,
    pub columns: usize,
    pub time_range: Option<crate::handlers::routes::metadata::TimeRange>,
    pub null_count: usize,
    pub non_finite_count: usize,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub(super) struct ManifestArtifactChecksums {
    pub source_dataset: String,
    pub source_schema: String,
    pub canonical_plan: String,
}

fn manifest_summary(
    data: &polars::prelude::DataFrame,
    time_column: &str,
) -> Result<ManifestDatasetSummary, AppError> {
    let metadata =
        crate::handlers::routes::metadata::build_dataset_metadata(data, false, Some(time_column))?;
    Ok(ManifestDatasetSummary {
        rows: metadata.total_rows,
        columns: metadata.columns.len(),
        time_range: metadata.time_range,
        null_count: metadata
            .column_profiles
            .iter()
            .map(|profile| profile.null_count)
            .sum(),
        non_finite_count: metadata
            .column_profiles
            .iter()
            .map(|profile| profile.non_finite_count)
            .sum(),
    })
}

pub(super) async fn build_handoff_manifest(
    state: &AppState,
    envelope: &PlanRequestEnvelope,
) -> Result<(DatasetVersionRecord, String, CleaningHandoffManifest), AppError> {
    let context = resolve_cleaning_context(state, envelope)?;
    let version = context.version;
    let plan_hash = context.plan_hash;
    let frame = context.frame;
    let root_version = state
        .dataset_versions()?
        .into_iter()
        .find(|candidate| candidate.id == version.root_id)
        .ok_or_else(|| AppError::internal("Cleaning manifest root source is unavailable"))?;
    let source = state.dataset_snapshot_for_version(&version.id)?;
    let (before, after) = tokio::try_join!(
        state.query_executor.execute_async(source),
        state.query_executor.execute_async(frame),
    )
    .map_err(AppError::from)?;
    let time_column = envelope.plan.time_column.clone();
    let (before, after) = state
        .query_executor
        .run_interactive(edatime_core::metrics::CpuStage::Analytics, move || {
            Ok::<_, AppError>((
                manifest_summary(&before, &time_column)?,
                manifest_summary(&after, &time_column)?,
            ))
        })
        .await
        .map_err(AppError::from)??;
    let manifest = CleaningHandoffManifest {
        schema_version: 1,
        exported_at: Utc::now(),
        execution_provenance: ManifestExecutionProvenance {
            application: "edatime-service",
            application_version: env!("CARGO_PKG_VERSION"),
            plan_schema_version: envelope.plan.schema_version,
            semantic_hash_algorithm: "fnv1a-v1",
            execution_mode: "exact-plan-v1",
        },
        source_version: version.clone(),
        root_source_version: root_version,
        plan_hash: plan_hash.clone(),
        canonical_plan: envelope.plan.clone(),
        before,
        after,
        artifact_checksums: ManifestArtifactChecksums {
            source_dataset: version.dataset_fingerprint.clone(),
            source_schema: version.schema_fingerprint.clone(),
            canonical_plan: plan_hash.clone(),
        },
    };
    Ok((version, plan_hash, manifest))
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct CleaningBundleChecksums {
    schema_version: u16,
    algorithm: &'static str,
    artifacts: BTreeMap<String, String>,
}

pub(super) fn sha256_hex(bytes: &[u8]) -> String {
    format!("sha256:{:x}", Sha256::digest(bytes))
}

/// Bundle independently usable, backend-generated handoff artifacts without
/// making browser code responsible for provenance or source generation.
pub(super) fn build_handoff_bundle(
    mut artifacts: Vec<(String, Vec<u8>)>,
) -> Result<Vec<u8>, AppError> {
    let checksums = artifacts
        .iter()
        .map(|(name, bytes)| (name.clone(), sha256_hex(bytes)))
        .collect::<BTreeMap<_, _>>();
    let index = CleaningBundleChecksums {
        schema_version: 1,
        algorithm: "sha256",
        artifacts: checksums,
    };
    artifacts.push((
        "checksums.json".to_string(),
        serde_json::to_vec_pretty(&index).map_err(|error| {
            AppError::internal(format!("Bundle checksum serialization failed: {error}"))
        })?,
    ));
    let mut archive = ZipWriter::new(Cursor::new(Vec::new()));
    let options = FileOptions::default().compression_method(CompressionMethod::Stored);
    for (name, bytes) in artifacts {
        archive.start_file(name, options).map_err(|error| {
            AppError::internal(format!("Bundle archive creation failed: {error}"))
        })?;
        archive
            .write_all(&bytes)
            .map_err(|error| AppError::internal(format!("Bundle archive write failed: {error}")))?;
    }
    archive
        .finish()
        .map(|cursor| cursor.into_inner())
        .map_err(|error| AppError::internal(format!("Bundle archive finalization failed: {error}")))
}
