#!/usr/bin/env node

import { readFile, writeFile } from 'node:fs/promises';
import process from 'node:process';

const contractUrl = new URL('../contracts/api-v1.json', import.meta.url);
const outputUrl = new URL('../docs/reference/api.md', import.meta.url);
const contract = JSON.parse(await readFile(contractUrl, 'utf8'));

function cell(value) {
    return String(value ?? '—').replaceAll('|', '\\|');
}

const rows = contract.operations.map((operation) =>
    `| \`${cell(operation.method)}\` | \`${cell(operation.path)}\` | ${cell(operation.request)} | ${cell(operation.response)} | \`${cell(operation.contentType)}\` | ${operation.planAware ? 'yes' : 'no'} |`,
);
const requiredHeaders = Object.entries(contract.headers)
    .filter(([, value]) => typeof value === 'string' && value.startsWith('x-'))
    .map(([name, value]) => `- \`${value}\` (${name})`)
    .join('\n');
const document = `# API Reference

<!-- Generated by scripts/generate_api_reference.mjs from contracts/api-v1.json. Do not edit route rows by hand. -->

Contract version: \`${contract.version}\`. Every application route is mounted only under \`${contract.basePath}\`; there is no unversioned compatibility router.

## Operations

| Method | Path | Request | Response | Content type | Plan-aware |
| --- | --- | --- | --- | --- | --- |
${rows.join('\n')}

## Response identity

Every response includes the request/build contract headers defined by the machine-readable contract:

${requiredHeaders}

Caller request IDs must follow this policy: ${contract.headers.requestIdCallerPolicy}

## Errors

Errors use \`${contract.error.contentType}\` and require these fields: ${contract.error.required.map((field) => `\`${field}\``).join(', ')}.

The JSON snapshot at \`GET ${contract.basePath}/metrics\` is intended for local diagnostics. \`GET ${contract.basePath}/metrics/prometheus\` exposes the same bounded, low-cardinality operational signals for scraping. Handler latency ends when a response is created; body latency ends when the response stream completes or is abandoned.
`;

if (process.argv.includes('--check')) {
    const existing = await readFile(outputUrl, 'utf8').catch(() => '');
    if (existing !== document) {
        process.stderr.write('docs/reference/api.md is stale; run node scripts/generate_api_reference.mjs\n');
        process.exit(1);
    }
    process.stdout.write(`API reference OK: ${contract.operations.length} operations\n`);
} else {
    await writeFile(outputUrl, document);
    process.stdout.write(`Generated API reference: ${contract.operations.length} operations\n`);
}
