export function downloadUrl(url: string, filename: string): void {
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  downloadUrl(url, filename);
  setTimeout(() => URL.revokeObjectURL(url), 10000);
}

export function downloadString(text: string, filename: string, mimeType = 'text/csv'): void {
  const blob = new Blob([text], { type: `${mimeType};charset=utf-8` });
  downloadBlob(blob, filename);
}

export function exportChartAsPNG(chartInstance: any, filename = 'edatime_chart.png'): void {
  if (!chartInstance) return;
  const canvas = chartInstance.getCanvas?.() ?? chartInstance.renderer?.canvas;
  if (canvas) {
    downloadUrl(canvas.toDataURL('image/png'), filename);
  }
}

export function exportChartAsCSV(
  xValues: Float64Array,
  series: Record<string, Float64Array>,
  filename = 'edatime_data.csv'
): void {
  const cols = Object.keys(series);
  const header = ['timestamp', ...cols].join(',');
  const rows: string[] = [header];
  const len = xValues.length;
  for (let i = 0; i < len; i++) {
    const x = new Date(xValues[i]).toISOString();
    const values = cols.map(c => {
      const v = series[c]?.[i];
      return v !== undefined ? String(v) : '';
    });
    rows.push([x, ...values].join(','));
  }
  downloadString(rows.join('\n'), filename, 'text/csv');
}

export function exportChartAsSVG(chartInstance: any, filename = 'edatime_chart.svg'): void {
  if (!chartInstance) return;
  const svg = chartInstance.exportSVG?.();
  if (svg) {
    downloadString(svg, filename, 'image/svg+xml');
  }
}

export function exportChartAsHTML(chartInstance: any, filename = 'edatime_chart.html'): void {
  if (!chartInstance) return;
  // Get the main chart canvas
  const canvas = chartInstance.getCanvas?.() ?? chartInstance.renderer?.canvas;
  if (!canvas) return;
  const chartDataUrl = canvas.toDataURL('image/png');

  // Try to get overlay canvas if present
  const overlayCanvas = document.querySelector('#timeseries-overlays canvas') as HTMLCanvasElement | null;
  const overlayDataUrl = overlayCanvas ? overlayCanvas.toDataURL('image/png') : '';

  // Build self-contained HTML
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Edatime Chart Export</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: #0f0f1a;
      color: #d2daf0;
    }
    .chart-container {
      position: relative;
      width: 100vw;
      height: 100vh;
    }
    .chart-img {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
    }
    .overlay-img {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      pointer-events: none;
    }
    .caption {
      position: absolute;
      bottom: 16px;
      left: 50%;
      transform: translateX(-50%);
      background: rgba(0, 0, 0, 0.6);
      padding: 6px 16px;
      border-radius: 4px;
      font-size: 12px;
      color: rgba(255, 255, 255, 0.7);
    }
  </style>
</head>
<body>
  <div class="chart-container">
    <img class="chart-img" src="${chartDataUrl}" alt="Edatime chart" />
    ${overlayDataUrl ? `<img class="overlay-img" src="${overlayDataUrl}" alt="Chart overlays" />` : ''}
    <div class="caption">Generated by Edatime</div>
  </div>
</body>
</html>`;

  downloadBlob(new Blob([html], { type: 'text/html' }), filename);
}

export function exportChartAsJSON(
  xValues: Float64Array,
  series: Record<string, Float64Array>,
  filename = 'edatime_data.json'
): void {
  const cols = Object.keys(series);
  const rows: object[] = [];
  const len = xValues.length;
  for (let i = 0; i < len; i++) {
    const row: Record<string, number | string> = { timestamp: xValues[i] };
    for (const c of cols) {
      row[c] = series[c]?.[i] ?? null;
    }
    rows.push(row);
  }
  downloadString(JSON.stringify(rows, null, 2), filename, 'application/json');
}